services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "1qaz@WSX"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./init:/init
    entrypoint: [ "/bin/bash", "-c", "echo 'Waiting for MSSQL to start...'; /opt/mssql/bin/sqlservr & sleep 30; /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 1qaz@WSX -i /init/init.sql; tail -f /dev/null" ]
    networks:
      - backend


  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql:1433;encrypt=false
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: 1qaz@WSX
    depends_on:
      - mssql
    ports:
      - "8080:8080"
    networks:
      - backend


networks:
  backend:
volumes:
  mssql-data: